/* ------------------------------------------------------------------ */
/*  Blog post index — verbatim from https://renoregen.com/blog/       */
/*  Order matches the live site (most recent first).                  */
/* ------------------------------------------------------------------ */

export type Post = {
  slug: string;
  title: string;
  date: string;
  image: string;
  excerpt: string;
  category: string;
};

export const POSTS: readonly Post[] = [
  { slug: "chiropractic-care-active-weekends-mountain-adventures", title: "Chiropractic Care for Active Reno Weekends and Mountain Adventures", date: "May 17, 2026", image: "/images/services/chiropractic-care.jpg", excerpt: "Move Better, Play Harder in Reno\u2019s Great Outdoors. Reno weekends are made for movement \u2014 river walks along the Truckee, laps up Peavine, hikes in the Sierra, paddling at Tahoe. Chiropractic care keeps weekend warriors aligned, mobile, and ready to recover.", category: "" },
  { slug: "habits-that-quietly-worsen-knee-pain", title: "Everyday Habits That Quietly Worsen Knee Pain in Reno", date: "May 10, 2026", image: "https://renoregen.com/wp-content/uploads/2026/05/pexels-towfiqu-barbhuiya-3440682-11103385.jpg", excerpt: "Simple Daily Choices That Make Knee Pain Worse Knee pain rarely shows up out of nowhere. For many people in Reno, it builds slowly over", category: "regenerative-medicine" },
  { slug: "backpackers-guide-sciatica-treatment-options", title: "Backpackers\u2019 Guide to Sciatica Treatment Options in Reno", date: "May 3, 2026", image: "https://renoregen.com/wp-content/uploads/2026/04/danka-peter-tvicgTdh7Fg-unsplash.jpg", excerpt: "Hit the Trail Without Sciatica Holding You Back Sciatica can turn a dream backpacking trip into a long, painful slog. If you hike with a", category: "regenerative-medicine" },
  { slug: "life-after-whiplash-when-seek-care", title: "Life After Whiplash: When to Seek Integrative Pain Care", date: "April 26, 2026", image: "https://renoregen.com/wp-content/uploads/2026/04/getty-images-3p8nseQ4rNs-unsplash.jpg", excerpt: "Whiplash can turn a small car accident into a big problem for your daily life. A simple rear-end tap on I-80 or a slow roll", category: "regenerative-medicine" },
  { slug: "regenerative-medicine-for-chronic-back-pain", title: "Understanding Regenerative Medicine for Chronic Back Pain", date: "April 19, 2026", image: "https://renoregen.com/wp-content/uploads/2026/04/getty-images-a7R1X-geveY-unsplash.jpg", excerpt: "Break Free From Chronic Back Pain This Spring Chronic back pain can touch every part of your day. It can make work harder, shorten family", category: "regenerative-medicine" },
  { slug: "is-regenerative-medicine-right-for-knee-pain", title: "Is Regenerative Medicine Right for Your Knee Pain?", date: "April 12, 2026", image: "https://renoregen.com/wp-content/uploads/2026/04/getty-images-41eTYbZh1pg-unsplash.jpg", excerpt: "Stop Letting Knee Pain Dictate Your Spring Plans Knee pain has a way of stealing the things you look forward to most. Walking local trails,", category: "regenerative-medicine" },
  { slug: "signs-back-pain-needs-spinal-decompression", title: "Warning Signs Your Back Pain Needs Spinal Decompression", date: "April 6, 2026", image: "https://renoregen.com/wp-content/uploads/2026/04/curated-lifestyle-Dg0ZC86AIgE-unsplash.jpg", excerpt: "When Back Pain Becomes More Than Just Sore Muscles Back stiffness after a long day outside, cleaning the garage, or catching up on yard work", category: "regenerative-medicine" },
  { slug: "why-your-knees-hurt-more-when-going-down-stairs-what-it-means-for-your-joint-health", title: "Why Your Knees Hurt More When Going Down Stairs: What It Means for Your Joint Health", date: "March 11, 2026", image: "https://renoregen.com/wp-content/uploads/2026/03/Lumii_20260311_121201424.jpg", excerpt: "Discover why your knees hurt when going down stairs and how knee decompression therapy in Reno can relieve pressure and restore joint function.", category: "" },
  { slug: "why-your-joints-feel-stiff-every-morning-what-your-body-is-trying-to-tell-you", title: "Why Your Joints Feel Stiff Every Morning: What Your Body Is Trying to Tell You", date: "March 11, 2026", image: "https://renoregen.com/wp-content/uploads/2026/03/Screenshot_20260311_001200_Gallery-1.jpg", excerpt: "Discover why your joints feel stiff every morning and how regenerative medicine and joint injections in Reno can restore mobility.", category: "" },
  { slug: "mood-swings-anxiety-irritability-when-hormones-not-stress-are-the-real-problem", title: "Mood Swings, Anxiety & Irritability: When Hormones \u2014 Not Stress \u2014 Are the Real Problem", date: "February 25, 2026", image: "https://renoregen.com/wp-content/uploads/2026/02/Screenshot_20260224_235810_Gallery.jpg", excerpt: "Discover how bioidentical hormone optimization in Reno can stabilize mood swings, reduce anxiety, and restore emotional balance.", category: "" },
  { slug: "why-youre-still-exhausted-after-8-hours-of-sleep-the-hidden-hormone-imbalance-most-people-miss", title: "Why You\u2019re Still Exhausted After 8 Hours of Sleep: The Hidden Hormone Imbalance Most People Miss", date: "February 25, 2026", image: "https://renoregen.com/wp-content/uploads/2026/02/Screenshot_20260224_234907_Google.jpg", excerpt: "Discover how bioidentical hormone therapy in Reno can correct hormone imbalance and restore energy, focus, and vitality.", category: "" },
  { slug: "the-knee-that-locks-up-why-it-happens-and-how-knee-decompression-can-free-your-movement", title: "The Knee That \u201cLocks Up\u201d: Why It Happens and How Knee Decompression Can Free Your Movement", date: "January 30, 2026", image: "https://renoregen.com/wp-content/uploads/2026/01/Lumii_20260130_004612231.jpg", excerpt: "Learn why your knee locks or stiffens and how non-surgical knee decompression in Reno can restore smooth, confident movement.", category: "" },
  { slug: "why-your-knee-feels-like-its-grinding-how-knee-decompression-can-ease-annoying-joint-catching", title: "Why Your Knee Feels Like It\u2019s Grinding: How Knee Decompression Can Ease Annoying Joint Catching", date: "January 30, 2026", image: "https://renoregen.com/wp-content/uploads/2026/01/Screenshot_20260130_003754_Gallery.jpg", excerpt: "Learn why your knee feels like it\u2019s grinding or catching and how knee decompression therapy in Reno can help relieve joint pressure.", category: "" },
  { slug: "struggling-with-dizziness-or-vertigo-physical-therapy-can-help-you-steady-yourself-in-reno", title: "Struggling With Dizziness or Vertigo? Physical Therapy Can Help You Steady Yourself in Reno", date: "December 16, 2025", image: "https://renoregen.com/wp-content/uploads/2025/12/iStock-1366196062.jpg.webp", excerpt: "Learn how vestibular physical therapy in Reno helps relieve dizziness, vertigo, and balance problems for safer, steadier movement.", category: "" },
  { slug: "after-the-fall-how-physical-therapy-in-reno-can-get-you-back-on-your-feet-safely", title: "After the Fall: How Physical Therapy in Reno Can Get You Back on Your Feet Safely", date: "December 16, 2025", image: "https://renoregen.com/wp-content/uploads/2025/12/Lumii_20251216_172212450.jpg", excerpt: "Learn how physical therapy in Reno helps you recover after a fall, restore mobility, and regain confidence in your balance.", category: "" },
  { slug: "recovering-from-surgery-why-post-operative-physical-therapy-is-the-key-to-faster-safer-healing", title: "Recovering From Surgery? Why Post-Operative Physical Therapy in Reno Is the Key to Faster, Safer Healing", date: "November 25, 2025", image: "https://renoregen.com/wp-content/uploads/2025/11/Screenshot_20251125_162446_Gallery.jpg", excerpt: "When you\u2019re recovering from surgery, each day can feel like a mix of hope, frustration, progress, and setback. Your body is healing, yet simple movements", category: "" },
  { slug: "from-stiff-to-strong-how-physical-therapy-in-reno-can-restore-your-mobility-after-years-of-joint-pain", title: "From Stiff to Strong: How Physical Therapy in Reno Can Restore Your Mobility After Years of Joint Pain", date: "November 25, 2025", image: "https://renoregen.com/wp-content/uploads/2025/11/istockphoto-1486145188-612x612-1.jpg", excerpt: "If you\u2019ve been living with stiffness or joint pain for months\u2014or even years\u2014you may have started to believe that this is simply the way your", category: "" },
  { slug: "knot-your-average-pain-how-trigger-point-injections-can-relieve-chronic-muscle-tension", title: "Knot Your Average Pain: How Trigger Point Injections in Reno Can Relieve Chronic Muscle Tension", date: "November 25, 2025", image: "https://renoregen.com/wp-content/uploads/2025/11/Screenshot_20251125_160748_Gallery.jpg", excerpt: "Do you ever feel like your body is one big knot? Your shoulders ache by midday, your neck feels stiff after working at your desk,", category: "" },
  { slug: "balancing-act-how-bioidentical-hormone-therapy-can-restore-your-vitality-and-well-being", title: "Balancing Act: How Bioidentical Hormone Therapy in Reno Can Restore Your Vitality and Well-being", date: "November 25, 2025", image: "https://renoregen.com/wp-content/uploads/2025/11/Lumii_20251125_155152829.jpg", excerpt: "Do you ever feel like your body is working against you? You wake up exhausted, even after a full night of sleep, or find yourself", category: "" },
  { slug: "reclaim-your-life-with-non-surgical-joint-injections-in-reno", title: "Reclaim Your Life with Non-Surgical Joint Injections in Reno", date: "September 28, 2025", image: "https://renoregen.com/wp-content/uploads/2025/09/photo-1614889997399-ffaa0cdb2427-scaled.jpeg", excerpt: "Discover how non-surgical joint injections in Reno can relieve chronic joint pain, improve mobility, and help you regain an active, pain-free lifestyle", category: "" },
  { slug: "how-nutritional-iv-therapy-can-combat-stress-fatigue", title: "How Nutritional IV Therapy Can Combat Stress & Fatigue", date: "September 28, 2025", image: "https://renoregen.com/wp-content/uploads/2025/09/photo-1517669375942-946a1f02d705-scaled.jpeg", excerpt: "Learn how personalized nutritional IV therapy in Reno can relieve stress, muscle fatigue, and boost your mental and physical performance.", category: "" },
  { slug: "get-rid-of-mid-back-stiffness-after-whiplash-without-surgery", title: "Get Rid of Mid Back Stiffness After Whiplash Without Surgery", date: "August 21, 2025", image: "https://renoregen.com/wp-content/uploads/2025/08/photo-1618914241652-ff0a094b5a86-scaled.jpeg", excerpt: "Reno Regenerative Medicine provides non-surgical relief for mid-back stiffness after whiplash using chiropractic care and spinal decompression", category: "" },
  { slug: "that-numbness-in-your-feet-when-walking-could-be-neuropathy", title: "That Numbness in your Feet when Walking Could Be Neuropathy", date: "August 21, 2025", image: "https://renoregen.com/wp-content/uploads/2025/08/photo-1643238232568-c67dc1ed4d5e-scaled.jpeg", excerpt: "If you feel buzzing numbness in your feet when walking, Reno Regenerative Medicine offers effective neuropathy relief with trigger point injections.", category: "" },
  { slug: "unlock-your-best-self-how-regenerative-medicine-boosts-hormone-health", title: "Unlock Your Best Self: How Regenerative Medicine Boosts Hormone Health", date: "July 13, 2025", image: "https://renoregen.com/wp-content/uploads/2025/07/Screen-Shot-2025-07-13-at-4.59.35-AM.png", excerpt: "Alright, let\u2019s talk about something truly important for feeling your best: your hormones. You see, these powerful little messengers in your body make everything tick", category: "regenerative-medicine" },
  { slug: "heal-and-thrive-the-power-of-regenerative-medicine", title: "Heal and Thrive: The Power of Regenerative Medicine", date: "June 29, 2025", image: "https://renoregen.com/wp-content/uploads/2025/06/Screen-Shot-2025-06-30-at-2.34.09-AM.png", excerpt: "Do you often feel held back by pain? Maybe your joints ache, your back hurts, or you just don\u2019t feel as strong and healthy as", category: "regenerative-medicine" },
  { slug: "do-you-suffer-from-these-symptoms-of-arthritis", title: "Do You Suffer from These Symptoms of Arthritis?", date: "July 14, 2021", image: "https://renoregen.com/wp-content/uploads/2021/07/2353750-1.jpeg", excerpt: "Arthritis is an umbrella term for about 100 different conditions that affect your joints. If you have arthritis, your joints are under attack. The attack", category: "" },
  { slug: "treat-your-sports-injury-with-chiropractic-care", title: "Treat Your Sports Injury with Chiropractic Care", date: "July 14, 2021", image: "https://renoregen.com/wp-content/uploads/2021/07/2364405.jpg", excerpt: "Sports Injury with Chiropractic Care Treating a sports injury with Chiropractic care works with your body to help it heal itself. At Reno Regenerative", category: "" },
];

export function getPost(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug: string, limit = 3): Post[] {
  const current = getPost(slug);
  const others = POSTS.filter((p) => p.slug !== slug);
  if (!current || !current.category) return others.slice(0, limit);
  const sameCat = others.filter((p) => p.category === current.category);
  const fill = others.filter((p) => p.category !== current.category);
  return [...sameCat, ...fill].slice(0, limit);
}
